name: ci-cd

on:
  push:
    branches: main
    paths:
      - "!docker-compose.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker image build -t gcr.io/${{ secrets.PROJECT_ID }}/golang-api:0.2  .

      - name: getting service account credential
        run: echo "$GCP_CREDENTIALS" > ./credential.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: authenticating service account
        run: gcloud auth activate-service-account --key-file credential.json

      - name: authenticating docker
        run: gcloud auth configure-docker --quiet

      - name: push docker image
        run: docker image push gcr.io/${{ secrets.PROJECT_ID }}/golang-api:0.2

      - id: deploy
        name: deploy to cloud run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ secrets.PROJECT_ID }}/golang-api:0.2
          service: golang-api
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          region: us-central1

      - name: Allow public access to api url
        run: gcloud run services add-iam-policy-binding golang-api --member="allUsers" --role="roles/run.invoker" --platform managed --region us-central1 --project ${{ secrets.PROJECT_ID }}

      - name: getting api version
        run: curl "${{ steps.deploy.outputs.url }}/version"